php artisan make:model servicio -m
php artisan make:model producto -m
php artisan make:model personaContacto -m
php artisan make:model cliente -m
php artisan make:model empleado -m
php artisan make:model orden -m
php artisan make:model detalleOrdenProducto -m
php artisan make:model detalleOrdenServicio -m
php artisan make:model contrato -m
php artisan make:model planilla -m
php artisan make:model empleadoPlanilla -m
php artisan make:model deposito -m
php artisan make:model proveedor -m
php artisan make:model mantenimiento -m
php artisan make:model insumo -m
php artisan make:model facturaInsumo -m
php artisan make:model detalleFacturaInsumo -m
php artisan make:model pagoEmpleado -m
php artisan make:model pagoMantenimiento -m
php artisan make:model pagoInsumo -m